global:
  resolve_timeout: 5m

route:
  receiver: default
  group_by: [alertname, team]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  routes:
    - match: {severity: critical, team: security}
      receiver: security-critical
      repeat_interval: 30m

    - match: {severity: critical, team: infra}
      receiver: infra-critical

    - match: {severity: critical, team: backend}
      receiver: backend-critical

    - match: {team: backend}
      receiver: backend-team

    - match: {team: security}
      receiver: security-team

    - match: {team: infra}
      receiver: infra-team

receivers:
  - name: default
    webhook_configs: []

  - name: infra-team
    webhook_configs: []

  - name: infra-critical
    webhook_configs: []

  - name: backend-team
    webhook_configs: []

  - name: backend-critical
    webhook_configs: []

  - name: security-team
    webhook_configs: []

  - name: security-critical
    webhook_configs: []

inhibit_rules:
  - source_match:
      severity: critical
    target_match:
      severity: warning
    equal: [alert_group]